### ISSUE TITLE
การ romanization ใช้กับชื่อผมไม่ได้

### ISSUE THREAD

**Issue by wasdee** [wannaphongcom/pythainlp#11]
```python
from pythainlp.romanization import romanization

b=romanization("ณัฐชนน")
print(b) #ṇạṭ̄h chnn 

b=romanization("นัด") + romanization("ชะ") + romanization("โนน") #ใช้สระโอะ ไม่ได้ ToT
print(b) #nạdchanon ดีขึ้นถ้าแยกทีละพยางค์

b="natchanon" #ที่ถูกคือ
print(b)
```

เป็นไปได้ไหมที่เราจะนำ [http://pioneer.chula.ac.th/~awirote/resources/thai-romanization.html](http://pioneer.chula.ac.th/~awirote/resources/thai-romanization.html) port มา

**Comment by wannaphongcom** [comment]
การตัดคำของ  http://pioneer.chula.ac.th/~awirote/resources/thai-romanization.html  ทำตามหลักเกณฑ์การถอดเสียงภาษาไทยเป็นอักษรโรมัน - http://www.arts.chula.ac.th/~ling/tts/ThaiRoman.pdf ของรัฐบาลที่ประกาศใช้ครับ แต่ในส่วน PyThaiNLP ใช้คำสั่งจาก icu ที่ใช้การ romanization ตามมาตราฐาน ISO 11940-2 - https://en.wikipedia.org/wiki/ISO_11940-2 ครับ การ romanization จึงไม่เหมือนกัน

ตอนริเริ่มทำโมดูลนี้ ผมเขียนตามหลักเกณฑ์การถอดเสียงภาษาไทยเป็นอักษรโรมัน https://github.com/wannaphongcom/pythainlp/blob/531b9177919ce2da15d8bc9b5320e77ef4b06f45/pythainlp/romanization/royin.py แต่มีปัญหา คือ ไม่รองรับสระภาษาไทยครับ ผมจึงตัดสินใจลบไฟล์แล้วใช้ ISO 11940-2 แทน หากคุณ @wasdee ต้องการสามารถนำ https://github.com/wannaphongcom/pythainlp/blob/531b9177919ce2da15d8bc9b5320e77ef4b06f45/pythainlp/romanization/royin.py ไปพัฒนาต่อให้รองรับสระแล้วส่งกลับมาได้ครับ ขอบคุณครับ

**Comment by wannaphongcom** [comment]
https://github.com/wannaphongcom/pythainlp/commit/7b32c8b39159b321be91ac4ea17f6a36cba60639

**Comment by wasdee** [comment]
ผมจะลองดูนะครับ

**Comment by wasdee** [comment]
นอกจากคำว่า พรม แล้วมีคำที่มีปัญหาอื่นๆไหมครับ ผมยังไม่ค่อยเข้าใจที่พูดว่าไม่รองรับสระ ช่วยอธิบายเพิ่มหน่อยครับ

**Comment by wannaphongcom** [comment]
ผมติดปัญหาตรงที่สระครับ ตัวอย่างเช่น
"สรรพ" คำนี้ใช้ รร (มีตัวสะกด) ได้เป็น sap
นี่คือปัญหาครับ จะตรวจสอบว่าเป็น รร (มีตัวสะกด) ได้อย่างไร ถ้าหากตรวจสอบไม่ได้ โปรแกรมอาจจะส่งค่ามาเป็น
sanp เป็น รร (ไม่มีตัวสะกด)
ครับ นอกจากนั้นยังมีปัญหาสระลดรูปในภาษาไทยตามที่ http://www.arts.chula.ac.th/~ling/tts/ThaiRoman.pdf กำหนดครับ

**Comment by wannaphongcom** [comment]
@wasdee  จาก https://github.com/wannaphongcom/pythainlp/commit/d8fda84c0b9cfeed5e0527e5e12cba1aaacfc41b ล่าสุด รองรับหลักเกณฑ์การถอดอักษรไทยเป็นอักษรโรมัน ฉบับราชบัณฑิตยสถานแล้วครับ
ผมลอง

```python
from pythainlp.romanization import romanization
b=romanization("นัด",engine="royin") + romanization("ชะ",engine="royin") + romanization("โนน",engine="royin") #ใช้สระโอะ ไม่ได้ ToT
print(b) # natchanon
```

ในการที่จะถอดทั้งคำได้เลย ต่อไปในอนาคตจะเพิ่มระบบแปลงเป็นคำอ่านต่อไปครับ
