### ISSUE TITLE
ไม่สามารถแบ่งคำที่มีภาษาอื่นปนอยู่ในประโยคได้ 

### ISSUE THREAD

**Issue by pawin** [wannaphongcom/pythainlp#14]
**English (without space)**
```
>>> a = "ผมชอบพูดภาษาไทยคำEnglishคำ"
>>> b = segment(a)
>>> b
['ผม', 'ชอบ', 'พูด', 'ภาษา', 'ไทย', 'คำEnglishคำ']
```
**English (with space)**
```
>>> a = "ผมชอบพูดไทยคำ English คำ"
>>> b = segment(a)
>>> b
['ผม', 'ชอบ', 'พูด', 'ไทย', 'คำ English คำ']
```
**Chinese**
```
>>> a =  "ผมมาจาก泰国ครับ"
>>> b = segment(a)
>>> b
['ผม', 'มา', 'จาก泰国ครับ']
```

**Comment by wannaphongcom** [comment]
จาก https://github.com/wannaphongcom/pythainlp/commit/08efca3f7e446b8ced9e9c6c6fb06a801407e395 ตอนนี้สามารถตัดคำไทยที่มี English (with space) รวมถึงภาษาอื่นที่มี space ได้แล้วครับ
```python
['ผม', 'ชอบ', 'พูด', 'ไทย', 'คำ', ' ', 'English', ' ', 'คำ']
```
แต่ที่ไม่มี space ไม่สามารถแยกออกจากคำไทยได้ เนื่องจาก PyICU ในคำสั่ง PyICU.BreakIterator.createWordInstance(PyICU.Locale("th"))  ไม่สามารถแยกตัวที่ติดกันได้ครับ  https://github.com/wannaphongcom/pythainlp/blob/develop/pythainlp/segment/pyicu.py

**Comment by wannaphongcom** [comment]
fix in https://github.com/wannaphongcom/pythainlp/commit/525f71d70b931c0a247747c1fc27c07139fc4d2f
