### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by gwohlgen** [wannaphongcom/pythainlp#16]
Hi @wannaphongcom , 

just installed the latest version of pythainlp on Redhat linux from the git sources.

When I try to use it I have the following problem:
```
import pythainlp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pythainlp-1.1-py2.7.egg/pythainlp/__init__.py", line 6, in <module>
    from pythainlp.romanization import *
TypeError: Item in ``from list'' not a string
```

From a quick web search it seems like there could be a python 2 / 3 issue with "unicode_literals".

Happy to get any feedback on how to solve this.

Cheers, Gerhard

**Comment by wannaphongcom** [comment]
fix in https://github.com/wannaphongcom/pythainlp/tree/develop

**Comment by gwohlgen** [comment]
Hi,

hmm,
now the next error when running the test script:

mæw
Traceback (most recent call last):
   File "test_gerhard.py", line 24, in <module>
     b=texttoeng(b)
   File "/home/gerhard/pythainlp/pythainlp/change/__init__.py", line 33, 
in texttoeng
     a = six.u(a)
   File "/usr/lib/python2.7/site-packages/six.py", line 621, in u
     return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
TypeError: decoding Unicode is not supported


seems like "a" is already unicode.

do you have a python2.7 environment for testing?

Thanks, Gerhard

**Comment by wannaphongcom** [comment]
@gwohlgen I have not a python2.7 environment for testing.

**Comment by wannaphongcom** [comment]
@gwohlgen  Now , PyThaiNLP support python 2.7 in https://github.com/wannaphongcom/pythainlp/commit/ad41eff8f41a08493f6484de456d68e07dfed292 .
test in https://travis-ci.org/wannaphongcom/pythainlp/jobs/217228168
