### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by gwohlgen** [wannaphongcom/pythainlp#17]
Hi,
thanks for fixing the import error!

tried to run your sample code now,
but still errors.

a) pythainlp/pythainlp/test/__init__.py", line 36 -- missing closing paranthesis .. easy to fix

but now:
```
[gerhard@localhost pythainlp]$ python test_gerhard.py
/home/gerhard/pythainlp/pythainlp/segment/dict.py:23: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if string == "":
Traceback (most recent call last):
  File "test_gerhard.py", line 6, in <module>
    b = segment(a)
  File "/home/gerhard/pythainlp/pythainlp/segment/dict.py", line 10, in segment
    result = tokenize(string, lines, "")
  File "/home/gerhard/pythainlp/pythainlp/segment/dict.py", line 27, in tokenize
    if string.startswith(pref):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)
```

when using:
```
# -*- coding: utf-8 -*-

# ตัดคำ
from pythainlp.segment import segment
a = 'ฉันรักภาษาไทยเพราะฉันเป็นคนไทย'
b = segment(a)
```

I am not sure if this is a problem with my system, or general one ..

Cheers, Gerhard

**Comment by wannaphongcom** [comment]
You setting the default encoding of python is utf8. https://stackoverflow.com/a/21190382 and reinstall from https://github.com/wannaphongcom/pythainlp/tree/develop

**Comment by gwohlgen** [comment]
Hi Wannaphong,

thank you, now I get further,
but still an error:

mæw
Traceback (most recent call last):
   File "test_gerhard.py", line 24, in <module>
     b=texttoeng(b)
   File "/home/gerhard/pythainlp/pythainlp/change/__init__.py", line 28, 
in texttoeng
     dictdataeng= {v: k for k, v in iteritems(dictdata)}
NameError: global name 'iteritems' is not defined


I hope I am not annoying :-)

Cheers, Gerhard

**Comment by wannaphongcom** [comment]
@gwohlgen fix in https://github.com/wannaphongcom/pythainlp/commit/241a5f7987a398febfdc43ee471fb51f53693d49

**Comment by wannaphongcom** [comment]
Now , PythaiNLP support python 2.7 in https://github.com/wannaphongcom/pythainlp/commit/ad41eff8f41a08493f6484de456d68e07dfed292 .
test in https://travis-ci.org/wannaphongcom/pythainlp/jobs/217228168
