### ISSUE TITLE
License for corpus

### ISSUE THREAD

**Issue by sura1997** [wannaphongcom/pythainlp#27]
Hi,

Are all *.txt files under https://github.com/wannaphongcom/pythainlp/tree/pythainlp1.4/pythainlp/corpus folder licensed under the Thai WordNet license (LICENSE_THA_WN)? What's the difference between thaiword.txt and new-thaidict.txt?

**Comment by wannaphongcom** [comment]
@sura1997 The WordNet license use only tha-wn.db.
The difference between thaiword.txt and new-thaidict.txt is  new-thaidict.txt has more data  than thaiword.txt.

**Comment by sura1997** [comment]
I think the new-thaidict.txt is really great. Is correct to say that new-thaidict.txt is a combination of words from Thai WordNet and additional data that you complied on your own? If so, what license of the additional data that you are releasing. Are you good with https://creativecommons.org/licenses/by-sa/4.0/?

**Comment by wannaphongcom** [comment]
@sura1997  Thank you.

**Comment by wannaphongcom** [comment]
fix in https://github.com/wannaphongcom/pythainlp/blob/pythainlp1.4/pythainlp/corpus/corpus_license.md
