### ISSUE TITLE
ทำไมถึงใช้ ICU เป็น default?

### ISSUE THREAD

**Issue by c4n** [wannaphongcom/pythainlp#34]
รู้สึกว่า ICU มันเป็นเครื่องมือตัดคำที่แย่มากครับ อยากรู้ว่าทำไมถึงเลือกเป็น default

**Comment by wannaphongcom** [comment]
@c4n เพื่อรักษาความเข้ากันได้กับคนที่ใช้ api ตัวนี้มาตั้งแต่เวชั่น 1.2 เป็นต้นมาครับ ใน PyThaiNLP 1.5 มีแผนจะเพิ่มการแจ้งเตือนเมื่อรันโค้ดว่า  default จาก ICU จะถูกเปลี่ยนไปเป็น newmm ในอนาคตคือ PyThaiNLP 1.6 ครับ
