### ISSUE TITLE
Can't symlink icu4c on OS X

### ISSUE THREAD

**Issue by kahnwong** [wannaphongcom/pythainlp#37]
Hi.

For some reason I can't symlink icu4c via ```brew link --force icu4c``` on OS X. Then, I installed it via ```brew install icu4c --HEAD``` and symlink(?) via

```
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile
```

Then I get this error when installing pythainlp:
> Please set the ICU_VERSION environment variable to the version of ICU you have installed.

Any ideas?

**Comment by wannaphongcom** [comment]
@kahnwong You can install icu. https://tobywf.com/2017/05/installing-pyicu-on-macos/

**Comment by kahnwong** [comment]
Works like a charm!
