### ISSUE TITLE
Long Term Support (LTS) version ?

### ISSUE THREAD

**Issue by wannaphongcom** [wannaphongcom/pythainlp#39]
ควรเลือก PyThaiNLP เวชั่นอะไรที่ควรเป็นรุ่น Long Term Support (LTS)  และควรมีระยะเวลา  Support เท่าไร

**Comment by c4n** [comment]
โปรเจคนี้ตอนนี้ไม่เห็นจำเป็นต้องมีLTSเลยครับ ถ้ากลัวใส่featureใหม่แล้วมีปัญหา ทำไม ไม่ทำเป็น stable version กับ  dev เวอชั่นแทน

**Comment by wannaphongcom** [comment]
@c4n ขอบคุณครับ ตอนนี้ผมมีแผนที่จะแยกหน้าหลักไป host ที่อื่นแทน GitHub ครับ โดยแยกเอกสาร stable กับ  dev ออกให้ชัดเจนครับ
