### ISSUE TITLE
Soundex bug

### ISSUE THREAD

**Issue by topskychen** [wannaphongcom/pythainlp#49]
https://github.com/wannaphongcom/pythainlp/blob/c1f414236c7351f0a2fe7d62f0d7f33da19de606/pythainlp/soundex.py#L44

Really appreciate your great work providing soundex alg for Thai. 
len(c) shoud be len(s), right?

**Comment by wannaphongcom** [comment]
No , c is characters from enumerate(s). https://github.com/wannaphongcom/pythainlp/blob/c1f414236c7351f0a2fe7d62f0d7f33da19de606/pythainlp/soundex.py#L31

**Comment by topskychen** [comment]
Thanks for quick response.  (i+1<len(c) and (c[i+1] in "ึืุู"), since `i` is the enumerate index for string s, by no means, you will use `c[i+1]`. I think it should be len(s) and s[i+1].

**Comment by wannaphongcom** [comment]
Thank you. I have already fixed.

**Comment by topskychen** [comment]
thank you ;)
