### ISSUE TITLE
Add windows 10 dependency installation to documentation

### ISSUE THREAD

**Issue by wasdee** [wannaphongcom/pythainlp#53]
การติดตั้ง pythainlp บน windows ต้องติดตั้ง pyicu ซึ่งทำได้ยากมาก
วิธีที่ง่ายที่สุดคือใช้ wheel

1. http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyicu แล้ว download wheel ตาม python ตัวเองเช่น
ผมใช้ python x64 3.6.1 บน Windows ก็ให้ใช้
PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl

2. `pip install PyICU‑1.9.7‑cp36‑cp36m‑win_amd64.whl`

3. `pip install pythainlp`

**Comment by wasdee** [comment]
[ส่วนตัว] @wannaphongcom ผมอยากเป็นเพื่อนด้วย แอดมาหน่อยนะครับ ผมเรียนอยู่ปี 4 วิศวคอมบางมด https://www.facebook.com/NutchnonNinyawee

**Comment by wannaphongcom** [comment]
@wasdee ผมหาเฟสไม่พบครับ เฟสผม https://www.facebook.com/tontanwannaphong

**Comment by wannaphongcom** [comment]
fix in https://github.com/wannaphongcom/pythainlp/commit/63dfb7efe7401b9e269fff85b32873382c37e021
